### ISSUE TITLE
100% CPU usage

### ISSUE THREAD

**Issue by yaroslavros** [wallix/redemption#12]
Rdpproxy works great and with passthrough session manager does exactly what I need it to do.
However, once a single RDP session is established, rdpproxy process consumes 100% of available CPU (33% user 66% system).
Is that expected?

Session is a simple passthrough without any recording/capture.

If this is not expected, what are the steps to troubleshoot this?

**Comment by yaroslavros** [comment]
Not sure if that's helpful, but looking at strace of rdpproxy I get a flood of following:

select(6, [3 4 5], [], NULL, {tv_sec=0, tv_usec=0}) = 0 (Timeout)

Some sort of busy loop... Is this intentional and expected?

**Comment by jonathanpoelen** [comment]
Which branch do you use? Does that happen with the `future` branch?

**Comment by yaroslavros** [comment]
I see that on master branch.

Have not tried future branch, but will give that a try!

-yaroslav
