### ISSUE TITLE
RDP to VNC function

### ISSUE THREAD

**Issue by ciari** [wallix/redemption#122]
I have compiled redemption on debian 10, everything works fine. But i couldnt figure out how to connect a VNC server. Is there any configuration option or connection parameter ?

**Comment by jonathanpoelen** [comment]
if you use `tools/passthrough/passthrough.py`, it only sends modules of type RDP or INTERNAL (depending on login). You need to add your own logic to have a VNC type module (line 315) and modify values of `proto_dest` and `target_protocol` (just above).

**Comment by ciari** [comment]
> if you use `tools/passthrough/passthrough.py`, it only sends modules of type RDP or INTERNAL (depending on login). You need to add your own logic to have a VNC type module (line 315) and modify values of `proto_dest` and `target_protocol` (just above).

great, i have figure it out, wrote to seperate systemd service files based on passthrough.py, i can push to git if i can complete my tests. But now another problem. I am trying to connect to tigervnc server on debian 10 with xfce desktep. VNCViewer connects without a problem. But over redemption i can only see black screen with mouse cursor. Below is the debug log if you can help me;




`
Feb 14 01:35:54 p19rdp rdpproxy: INFO (7682/7682) -- Creation of new mod 'VNC'
Feb 14 01:35:54 p19rdp rdpproxy: INFO (7682/7682) -- create_module_vnc::timer_events_.create_timer_executor
Feb 14 01:35:54 p19rdp rdpproxy: INFO (7682/7682) -- ModuleManager::Creation of new mod 'VNC' suceeded
Feb 14 01:35:54 p19rdp rdpproxy: INFO (7682/7682) -- check_acl remote_answer signal=BACK_EVENT_NONE
Feb 14 01:35:54 p19rdp rdpproxy: INFO (7682/7682) -- Back Event NONE
Feb 14 01:35:54 p19rdp rdpproxy: INFO (7682/7682) -- Server Protocol Version=3.8
Feb 14 01:35:54 p19rdp rdpproxy: INFO (7682/7682) -- got 2 security types:
Feb 14 01:35:54 p19rdp rdpproxy: INFO (7682/7682) -- * VeNCrypt
Feb 14 01:35:54 p19rdp rdpproxy: INFO (7682/7682) -- * VNC
Feb 14 01:35:54 p19rdp rdpproxy: INFO (7682/7682) -- VeNCrypt security choosen
Feb 14 01:35:54 p19rdp rdpproxy: DEBUG (7682/7682) -- VeNCrypt subtypes:
Feb 14 01:35:54 p19rdp rdpproxy: DEBUG (7682/7682) --  * VNC
Feb 14 01:35:54 p19rdp rdpproxy: DEBUG (7682/7682) --  * TLS VNC
Feb 14 01:35:54 p19rdp rdpproxy: DEBUG (7682/7682) -- selected VeNCrypt security is VNC
Feb 14 01:35:54 p19rdp rdpproxy: INFO (7682/7682) -- Receiving VNC Server Random
Feb 14 01:35:54 p19rdp rdpproxy: INFO (7682/7682) -- Receiving VNC Server Random
Feb 14 01:35:54 p19rdp rdpproxy: INFO (7682/7682) -- Sending Password
Feb 14 01:35:54 p19rdp rdpproxy: INFO (7682/7682) -- Waiting for password ack
Feb 14 01:35:54 p19rdp rdpproxy: INFO (7682/7682) -- Waiting for password ack
Feb 14 01:35:54 p19rdp rdpproxy: INFO (7682/7682) -- vnc password ok
Feb 14 01:35:54 p19rdp rdpproxy: INFO (7682/7682) -- enable ZRLE encoding
Feb 14 01:35:54 p19rdp rdpproxy: INFO (7682/7682) -- enable RAW encoding
Feb 14 01:35:54 p19rdp rdpproxy: INFO (7682/7682) -- enable copyrect encoding
Feb 14 01:35:54 p19rdp rdpproxy: INFO (7682/7682) -- enable cursor pseudo encoding
Feb 14 01:35:54 p19rdp rdpproxy: INFO (7682/7682) -- Server_resize: Resizing client to : 1900 x 1200 x 24
Feb 14 01:35:54 p19rdp rdpproxy: INFO (7682/7682) -- Server_resize: starting client deactivation/reactivation sequence
Feb 14 01:35:54 p19rdp rdpproxy: INFO (7682/7682) -- Front::send_demand_active()
Feb 14 01:35:54 p19rdp rdpproxy: INFO (7682/7682) -- resizing done
Feb 14 01:35:54 p19rdp rdpproxy: WARNING (7682/7682) -- Waiting for client become up and running
Feb 14 01:35:54 p19rdp rdpproxy: INFO (7682/7682) -- ultimatum (front must notify resize) = 0.0 s
Feb 14 01:35:54 p19rdp rdpproxy: INFO (7682/7682) -- ultimatum (front must notify resize) = 0.0 s
Feb 14 01:35:54 p19rdp rdpproxy: INFO (7682/7682) -- ultimatum (front must notify resize) = 0.0 s
Feb 14 01:35:54 p19rdp rdpproxy: INFO (7682/7682) -- ultimatum (front must notify resize) = 0.0 s
Feb 14 01:35:54 p19rdp rdpproxy: INFO (7682/7682) -- ultimatum (front must notify resize) = 0.0 s
Feb 14 01:35:54 p19rdp rdpproxy: INFO (7682/7682) -- ultimatum (front must notify resize) = 0.0 s
Feb 14 01:35:54 p19rdp rdpproxy: INFO (7682/7682) -- ultimatum (front must notify resize) = 0.0 s
Feb 14 01:35:54 p19rdp rdpproxy: INFO (7682/7682) -- ultimatum (front must notify resize) = 0.0 s
Feb 14 01:35:54 p19rdp rdpproxy: INFO (7682/7682) -- ultimatum (front must notify resize) = 0.0 s
Feb 14 01:35:54 p19rdp rdpproxy: INFO (7682/7682) -- ultimatum (front must notify resize) = 0.0 s
Feb 14 01:35:54 p19rdp rdpproxy: INFO (7682/7682) -- ultimatum (front must notify resize) = 0.0 s
Feb 14 01:35:54 p19rdp rdpproxy: INFO (7682/7682) -- ultimatum (front must notify resize) = 0.0 s
Feb 14 01:35:54 p19rdp rdpproxy: INFO (7682/7682) -- ultimatum (front must notify resize) = 0.0 s
Feb 14 01:35:54 p19rdp rdpproxy: INFO (7682/7682) -- ultimatum (front must notify resize) = 0.0 s
Feb 14 01:35:54 p19rdp rdpproxy: INFO (7682/7682) -- ultimatum (front must notify resize) = 0.0 s
Feb 14 01:35:54 p19rdp rdpproxy: INFO (7682/7682) -- ultimatum (front must notify resize) = 0.0 s
.. --SHORTENED REPEATING MSG--
Feb 14 01:35:54 p19rdp rdpproxy[7674]: rdpproxy: INFO (7682/7682) -- ultimatum (front must notify resize) = 0.0 s
Feb 14 01:35:54 p19rdp rdpproxy[7674]: rdpproxy: INFO (7682/7682) -- ultimatum (front must notify resize) = 0.0 s
Feb 14 01:35:54 p19rdp rdpproxy[7674]: rdpproxy: INFO (7682/7682) -- ultimatum (front must notify resize) = 0.0 s
Feb 14 01:35:54 p19rdp rdpproxy[7674]: rdpproxy: INFO (7682/7682) -- ultimatum (front must notify resize) = 0.0 s
Feb 14 01:35:54 p19rdp rdpproxy[7674]: rdpproxy: INFO (7682/7682) -- ultimatum (front must notify resize) = 0.0 s
Feb 14 01:35:54 p19rdp rdpproxy[7674]: rdpproxy: INFO (7682/7682) -- ultimatum (front must notify resize) = 0.0 s
Feb 14 01:35:54 p19rdp rdpproxy[7674]: rdpproxy: INFO (7682/7682) -- ultimatum (front must notify resize) = 0.0 s
Feb 14 01:35:54 p19rdp rdpproxy[7674]: rdpproxy: INFO (7682/7682) -- ultimatum (front must notify resize) = 0.0 s
.. --SHORTENED REPEATING MSG--
`

thanks in advance

**Comment by jonathanpoelen** [comment]
Which branch have you tried? Have you tried with the `future` branch?

**Comment by ciari** [comment]
alright future branch has solution. Thanks alot
