### ISSUE TITLE
Shared properties in passthrough.py seem to be ignored

### ISSUE THREAD

**Issue by alexandru-bagu** [wallix/redemption#133]
I've been trying, to no avail, to disable clipboard or even change the bpp (seemed to be the simplest way to test my theory). No matter what I try there seems to be no change.

I tried to add the following lines right after: https://github.com/wallix/redemption/blob/26f96d1b52b28482a4737022a1158e399e5e2bd1/tools/passthrough/passthrough.py#L314
```
        kv[u'bpp'] = u'8'
        kv[u'mod_rdp:session_probe_use_clipboard_based_launcher'] = u'0'
```
I also tried u'disallow' or u'False' instead of u'disallow' but that made no difference.
Additionally I got the names for the keys from `projects/redemption_configs/autogen/doc/sesman_dialog.txt`.

Is this not the way it's supposed to be done? Am I doing something wrong?

**Comment by jonathanpoelen** [comment]
Sorry, `opt_width`/`width`, `opt_height`/`height` and `opt_bpp`/`bpp` are never read by the proxy, only written.

To disable the clipboard, you must put the value `cliprdr` in `deny_channels`.

You can see variables transmitted and received between passthrough and the proxy by adding `[debug] auth=0x2` in `rdpproxy.ini`.

**Comment by alexandru-bagu** [comment]
@jonathanpoelen many thanks.
