### ISSUE TITLE
Keyboard events logging

### ISSUE THREAD

**Issue by hellrai5er** [wallix/redemption#157]
Hello! I managed video capture to wrm file but I can't configure keyboard events capture. How to enable keyboard logging into a text/syslog file? Help me please

**Comment by XiaopengZHOU** [comment]
You can put the following lines in your **/etc/rdpproxy/rdpproxy.ini**:

`[video]`
`disable_keyboard_log=none`

**Comment by hellrai5er** [comment]
I have created an empty ini file /etc/rdpproxy/rdpproxy.ini and added following strings. Nothing happened. 

I have configured video capture via a python file (by uncomment string "is_rec")

**Comment by XiaopengZHOU** [comment]
Please try this:

`[session_log]`
`keyboard_input_masking_level=0`

**Comment by hellrai5er** [comment]
... and still not happened(((

**Comment by hellrai5er** [comment]
now i have ini file like this: 

[video]
disable_keyboard_log=none

[session_log]
enable_session_log = 1
keyboard_input_masking_level=0
there are only 3 files per session in var/rdpproxy/recorded/rdp directory: .wrm file, .mwrm file and .log file without keyboard events

**Comment by jonathanpoelen** [comment]
`disable_keyboard_log` is now in `[capture]` section

```ini
[capture]
disable_keyboard_log=none


[session_log]
enable_session_log = 1
keyboard_input_masking_level=0
```

**Comment by hellrai5er** [comment]
Thank you so much! it's ok now
