### ISSUE TITLE
Necessity of passthrough.py

### ISSUE THREAD

**Issue by nemliyartym** [wallix/redemption#158]
Hello, I'm looking into your project. Tell me please what you are using passthrough.py and socket '/tmp/redemption-sesman-sock'? 

As I understand it, this process is only needed for authentication and forwarding credentials.

**Comment by jonathanpoelen** [comment]
passthrough.py is used to exchange authentication and credentials with the proxy, but also to configure some options associated to a session (like recording and some of the values that can be found in the redemption ini file). It is also passthrough.py that decides which module to use (ask for login, mdp and target, display a list of targets, etc).

The socket is used to exchange messages between the proxy and passthrough.py. The socket is configurable in the ini file of redemption.

**Comment by nemliyartym** [comment]
Thanks for the help
