### ISSUE TITLE
Add custom fields to the login screen

### ISSUE THREAD

**Issue by nemliyartym** [wallix/redemption#160]
Hey guys!
I'm trying to add additional data entry fields to the login screen.
I found the `globals` structure, in which, following the example of `target_device`, I added my `data` structure and updated the index and section sizes. Then in `acl_auth_info `I call `ini.ask<cfg::globals::data>()`

But when creating a session I get the following errors:
```
rdpproxy: WARNING (6422/6422) -- ◢ In projects/redemption_configs/redemption_src/configs/config.cpp:57
rdpproxy: WARNING (6422/6422) -- parsing error with acl parameter 'formflag' for "interactive_target": bad format, expected decimal, hexadecimal
```
Am I moving in the right direction?
Help me please :(

**Comment by nemliyartym** [comment]
I figured out how to add a parameter to the config. Now I'm trying to figure out how I can create a data entry field

**Comment by jonathanpoelen** [comment]
You will have to add your field in `src/mod/internal/widget/login.cpp` (this is very manual...) and complete the event `onsubmit` in `src/mod/internal/login_mod.cpp`. Don't forget to add your variable in `LoginModVariables` (.hpp) which restricts access to config variables.

The easiest way is to put your field with target or login and do a little parsing in the python code.

**Comment by nemliyartym** [comment]
> You will have to add your field in `src/mod/internal/widget/login.cpp` (this is very manual...) and complete the event `onsubmit` in `src/mod/internal/login_mod.cpp`. Don't forget to add your variable in `LoginModVariables` (.hpp) which restricts access to config variables.
> 
> The easiest way is to put your field with target or login and do a little parsing in the python code.

Thanks for the help! I managed to add an input field to change the code iteractive_target. But today I will try your way.
