### ISSUE TITLE
Redrec help is wrong about seconds in --begin and --end; wrong timestamp (1970) when --begin is used

### ISSUE THREAD

**Issue by sdbbs** [wallix/redemption#165]
Using this:

```none
$ redrec --version
ReDemPtion 10.4.41 (gcc 9.4.0)
Copyright (C) Wallix 2010-2020
```

... I get the help on `--begin` and `--end`:

```none
$ redrec --help | grep 'capture time'
  -b, --begin=<seconds>               begin capture time (in seconds)
  -e, --end=<seconds>                 end capture time (in seconds)
```

So, the way it is written, I get that `--begin` sets the beginning of the capture in seconds *after the beginning of the capture*, that is, it has the meaning of "begin after so many seconds after capture start".

So I check how long is my capture:

```none
$ redrec --quick=on --meta=on -i $PWD/01\:02-2ea54801-6e40-47a3-bf78-725a10be81ca.mwrm 
redrec: INFO (397616/397616) -- player begin_capture = 0

WRM file version      : 4
Width                 : 1280
Height                : 720
Bpp                   : 16
Cache 0 entries       : 600
Cache 0 size          : 768
Cache 1 entries       : 300
Cache 1 size          : 3072
Cache 2 entries       : 262
Cache 2 size          : 12288
Compression algorithm : 1
RemoteApp session     : No
Duration (in seconds) : 28519
```

Great, it is 28519 seconds, that is, 7.9 hours. So I would like to skip the first 3.6 hours, which is about 220 mins, which is 13200 seconds. 13200 seconds is smaller than total duration 28519, so I should be OK setting the beginning there, right? Well, after some minutes of waiting for the command below, I got:

```none
$ redrec --encryption=disable --video=on --full=on --frame-rate=25 --begin=13200 -i $PWD/01\:02-2ea54801-6e40-47a3-bf78-725a10be81ca.mwrm -o $PWD/out.mp4
Output file is "/tmp/recorded/2023-03-29/out.mp4".
Asked time not found in mwrm file
```

What do you mean "not found"? Where were you looking, `redrec` - or rather, what was the range you inspected? It would have been SO nice if someone wrote the error message to be:

> Asked time (13200) not found in mwrm file (searched from XXXX to YYYY)

But no, of course, where would the excitement (and lost time) be then?

So of course, I then have to remember that the only other "seconds" I know of are Unix timestamps - but those are also datetimes, not just "seconds"! And just to double-check:

![image](https://user-images.githubusercontent.com/48317456/228528881-252dc39f-da00-4a0e-96af-7d9175c679d4.png)

Yup, I can see "time_since_epoch" there - that can be nothing else than a Unix timestamp!

So I found the approximate Unix timestamp "now" with:

```
$ date ; date +%s
Wed 29 Mar 2023 04:55:14 AM CEST
1680058514
```

... and approximate start of the region I was interested in was 10 minutes before that, so at 1680058514-600 = 1680057914; so then I tried:

```none
$ redrec --encryption=disable --video=on --full=on --frame-rate=25 --begin=1680057914 -i $PWD/01\:02-2ea54801-6e40-47a3-bf78-725a10be81ca.mwrm -o $PWD/out.mp4
```

... and this finally worked.

It would have been so, so much easier, if anyone cared enough, just to insert just a two words per line more in the `--help`:

```
  -b, --begin=<seconds>               begin capture time (Unix timestamp, in seconds)
  -e, --end=<seconds>                 end capture time (Unix timestamp, in seconds)
```

------

EDIT: turns out, there is a bug here too: if `--begin` is used and timestamp view is enabled, then one gets 1970 in the timestamp date - this is an edit based from an exported .png from redrec:

![2023-03-29_first-000001](https://user-images.githubusercontent.com/48317456/228689815-8f8bcc4f-b99e-4ae9-939b-a7a10f169aad.png)

If `--begin` is not used, then the timestamp is fine:

![2023-03-29_second-000001](https://user-images.githubusercontent.com/48317456/228689878-7b2c1b5e-282b-431d-98fe-fa1be0f60a4b.png)

**Comment by jonathanpoelen** [comment]
now `--begin` and `--end` options support timestamp and relative time. There is also a simplified format of the form `HH:MM:SS` / `MM:SS`

the following 3 ways are equivalent
```
--begin 5586
--begin 93:6
--begin 1:33:6
```
