### ISSUE TITLE
Future branch bugs

### ISSUE THREAD

**Issue by rzbsh** [wallix/redemption#168]
Hi,

I tried to use Future branch but had many problems like python function in passthrough.py didn't return expected value, rdpproxy couldn't make directory to save the captured videos, and some other problems. It needs some modifications to works. But maintenance_bastion_10.4 works out of the box.
Did I miss something or it's just like that?

**Comment by rzbsh** [comment]
passthrough.py line 244 clears the password.
`if len(splitted) == 2:`
`            login = splitted[0]`
`            host = splitted[1]`
`            device = host`
`            password = ''`

**Comment by jonathanpoelen** [comment]
Indeed, this is not a good idea outside of internal modules. I've just made a change for that.

As passthrough.py is now usable, I'm closing this issue.
