### ISSUE TITLE
Centos 7 compilation

### ISSUE THREAD

**Issue by philzyk** [wallix/redemption#19]
Hello!
Great tool! I was looking for rdp-proxy for long time and using haproxy as rdp-proxy via rdp-cookie, but your solution is much more flexible.
Sorry, i'am not a developer, so i want to ask, probably, silly question - is it possible to compile your tool on CentOS 7?
Thank you very much!

**Comment by pykoder** [comment]
Possible to compile redemption on CentOS... theoretically yes. In practice, no.

But it will be really hard. You will have to compile your compiler (the default compiler of CentOS is not compatible with up to date gcc compiler, redemption will need Gcc 7 for c++14 support). redemption also does have some dependencies on other packages (including bjam and build tools) and you will likely have to build everything from sources as centSO packages are really old. Henceforth, unless you have a very good reason to stick to centOS 7, it's certainly much easier to compile redemption for a more recent distro. Compiling redemption for centOS wouldn't event be easy for me and would certainly take me an unreasonable amount of time, while installing a modern distro is a matter of hours.

**Comment by jonathanpoelen** [comment]
The latest version of Ubuntu (18.04 LTS). Compared to the README, everything is in the repositories except `libgssglue-dev`, but it works without. The `libavcodec-ffmpeg56`, `libavformat-ffmpeg56`, `libavutil-ffmpeg54` and `libswscale-ffmpeg3` packages do not need to be installed because they depend on `*-dev` packages (and the versions are different).

This should work:
```bash
git clone --recursive https://github.com/wallix/redemption
cd redemption
sudo apt install -y g++
sudo apt install -y libboost-tools-dev libboost-test-dev libssl-dev libkrb5-dev libgssglue-dev libsnappy-dev libpng-dev
sudo apt install -y libavcodec-dev libavformat-dev libavutil-dev libswscale-dev libx264-dev libbz2-dev
sudo apt install -y libavcodec-extra
bjam rdpproxy
```
