### ISSUE TITLE
remoteapp: proxy windows

### ISSUE THREAD

**Issue by speidy** [wallix/redemption#24]
Hi,

I tested RemoteApp through the proxy (using passthrough authentifier)
I always get the AdminBastion window. Is it expected?

How do I proxy RemoteApps from the 3rd party remote host ?

**Comment by jonathanpoelen** [comment]
Hi,

It was decided to do something more usable than the current passthrough.py and closer to what we use.

In the meantime, you can look at the associated commit to see which variables to use.

**Comment by mengtan** [comment]
You can now proxy RemoteApps with passthrough authentifier if you input some special syntax in Device edit box:
<host>$<application path>$<working dir>$<args>
for exemple:
192.168.1.1$C:\\Windows\System32\\notepad.exe$C:\\Windows$

**Comment by speidy** [comment]
Thank you both 👍
