### ISSUE TITLE
How to use this project

### ISSUE THREAD

**Issue by jimmy201602** [wallix/redemption#25]
I've been  compile this project successfully? I have not find any document how to use this project?

**Comment by pykoder** [comment]
RTFM. Haven't you found README.md ?

**Comment by jimmy201602** [comment]
``` A dialog box should open in which you can type a username and a password. With default authhook at least internal services should work. Try login: bouncer and password: bouncer, or login: card and password: card. To access your own remote RDP hosts you'll of course have to configure them in authhook.py. Hopefully at some time in the future these won't be hardcoded, but authhook.py will access to some configuration file. If you want to provide such extensions to current authhook.py, please contribute it, it will be much appreciated.```
I haven't find the authhook.py file. So I confuse about that.

**Comment by jonathanpoelen** [comment]
The part about `authhook.py` is out of date and has been replaced by` passthrough.py`. Currently, the internal bouncer module is not accessible without modification of `passthrough.py` and only the interactive login is used.

We are aware that it is difficult to change this part without knowing how the proxy works, but the clarification work has not started. If you want to modify this part, you can read the variables passed between the proxy and passthrough.py with the calls to `W.member` in the file `projects/redemption_configs/configs_specs/configs/specs/config_spec.hpp` file. (and `...../config_type.hpp` for some lists of values).
