### ISSUE TITLE
how to change "Device" field to pop-up menu?

### ISSUE THREAD

**Issue by hadadiashkan** [wallix/redemption#28]
I want to modify the project in a way to provide a list of servers, rather than entering destination IP address and then client is able to select a target. i don't know how to do that.
Thanks for guiding me through that.

**Comment by pykoder** [comment]
This is rather complicated to do. The project provides some internal pages dedicated to that kind of thing (the default page where you can type the destination IP is one of such pages) and what is available is not a popup. What you need is the "selector" page and you have to provide the list of targets it will show.  No need to modify the project for that, everything can be controlled from the external python script.

But it will be easier to provide you with a sample python Authentifier script as an example than explaining. I will had one to the repository as soon as I have time to write it and will let you know.

**Comment by hadadiashkan** [comment]
Thank you very much for your help. I'll wait.

**Comment by jonathanpoelen** [comment]
You can have the selector module with the `selector` value for the `module` field (i.e. `kv[u'module'] = 'selector'`).

Then it gets complicated.

- The `target_login`,  `target_device` et `proto_dest` fields are value lists separated by a `\x01` character (i.e. `kv[u'target_device'] = 'target 1\x01target 2\x01target 3...'`).

- To know what modules and passthrough.py can communicate, you can look at the beginning of `src/mod/internal/*.hpp` files:

```cpp
// src/mod/internal/flat_login_mod.hpp
// vcfg::var<field_name_in_the_proxy>
// vcfg::accessmode: what does the module do with the field
// - ::set = send the value
// - ::get = read the value
// - ::ask = ask the value
using FlatLoginModVariables = vcfg::variables<
    vcfg::var<cfg::globals::auth_user, vcfg::accessmode::set>,
    // ...
>;
```

- The correspondence between the names in the proxy and passthrough.py are in `projects/redemption_configs/configs_specs/configs/specs/config_spec.hpp`

```cpp
W.section("globals", [&] {
  // ...
  // sesman = passthrough (optional. If absent, is identical to the field name; here "auth_user")
  W.member(no_ini_no_gui, sesman_rw, L, type_<std::string>(), "auth_user", sesman::name{"login"});
  // ...
});
```

This line means that the `login` field of passthrough.py matches the name `cfg::globals::auth_user` in the proxy.

- The names of the modules are in `src/acl/module_manager/enums.hpp`.

**Comment by hadadiashkan** [comment]
I acted as you said. But the list was not created. @jonathanpoelen
![screenshot from 2019-01-28 15-03-04](https://user-images.githubusercontent.com/24314881/51834037-5a1ee800-230e-11e9-973d-c5548371fce2.png)

**Comment by hadadiashkan** [comment]
I forgot to change the port part. You're right

**Comment by hadadiashkan** [comment]
![screenshot from 2019-02-06 10-27-14](https://user-images.githubusercontent.com/24314881/52325324-d645b980-29f9-11e9-89df-4cdbfe629974.png)

I did what you said and it showed the list, but when I click on the connection button, it doesn't work.

**Comment by jonathanpoelen** [comment]
The proxy sends selection and clicks information to `passthrough.py`. It is the latter who decides to move to the next module (as is the case in the current version with the transition box login -> session rdp).

**Comment by hadadiashkan** [comment]
So after all, should I use the .recv() method to get the information, and then I will update the kv dictionary(using RDP module) and resend it?
