### ISSUE TITLE
Feature request: Enable authentifier to validate target server certificates

### ISSUE THREAD

**Issue by jukeks** [wallix/redemption#32]
# Motivation

Many RDP hosts might not have domain CA signed server certificates which could be validated by chain validation. Many RDP hosts might not even be part of a domain. This leads to certificate pinning with TOFU.

ReDemPtion currently can store pinned certificates to filesystem with the option "server_cert_store". This is fine for single node systems, but in a multi node system it would lead to cert stores being out of sync and thus allowing MITM attacks.

# Solution

Allow target RDP certificate to be passed to authentifier for validation and global storing.

# Implementation plan

* Add a callback function to ServerNotifier interface than would be called in TlsContext::check_certificate if set.
* Add a new field to "module" = "RDP" message (not sure if "VNC" or "XUP" are applicable) that would trigger passing server certificate for validation, for example "server_cert_callback" = "1"

I am willing to implement this, but is this something you would consider integrating given a pull request? Does the implementation plan sound reasonable?

**Comment by pykoder** [comment]
Hi Juke (don't know if it's the correct way to address you, correct me if necessary), you can call me Christophe (pykoder),

What you suggest looks like a good idea, certificate management should indeed be deferred to authentifier, this can help fixing the problem you spotted and other potential issues. Your suggested implementation plan is also basically ok, but it raises an issue. We will have to make enable_client_tls in socket_transport asynchronous and enter a wait state (with also a timeout) until authentifier has given it's answer. This will also means not waking mod_rdp process even if server socket has waiting data. That means managing a new wake-up case where we have server data waiting, but ignore them until we get some answer from authentifier or timeout.

We will also have to take into account effect on our stand alone RDP client which does not have an identifier at all.

Nevertheless the expected improvement is important enough for us to consider helping you making the involved changes.

What you can do now if you like is provide new code working the way you see it, but that can be enabled/disabled through a configuration flag so we can switch between old behavior and new proposed behavior, then we will work out the asynchronicity issues.

Regards,
Christophe Grosjean

**Comment by jukeks** [comment]
Great!

I've started implementing the feature. It will take sometime since this a complete new code base for me. You can see the progress at #33.

A couple of questions:
1. How do you use the branches? Should I develop against future or master?
2. Should https://github.com/jukeks/redemption/blob/future/src/transport/socket_transport.cpp#L155 rather assert that `ret == Transport::TlsResult::Ok` since not all error conditions throw like https://github.com/wallix/redemption/blob/future/src/system/linux/system/tls_context.hpp#L255 ?

**Comment by jonathanpoelen** [comment]
1. Do your development on future. Master is used when tagging.
2. I think the assert only exists because the current code does not support any other value than `Ok` or `Fail` for `check_certificate`. In reality, it is enough to add a state in TLSState and adapt the function accordingly.

**Comment by jukeks** [comment]
Rebased the branch to future on #33.

Is there any prior art in sending multiline messages in the sesman/authentifier protocol? I was thinking of sending the certificate as PEM encoded string, but that has newlines. Would it be better to use base64 encoded DER? Do you have base64 encoding implemented somewhere in the product?

I think I'm now at the point that I need some guidance in the architecture department and and some review on how badly I'm mutilating your interfaces. Also I don't have a good idea on how to wait for the response from authentifier after ini.asking certificate's validity.

**Comment by jonathanpoelen** [comment]
This is a big limitation of sesman. Currently, the few messages with line breaks are intended for widgets and use `<br>` as a replacement. Perhaps the easiest way would be to replace the `\n` by `\x01`? Otherwise there is a `unbase64` function in `src/capture/cryptofile.hpp` that is not used.

For the callback, you need 3 states: "failed", "ok" and "pending" for the sesman's answer and forward it to https://github.com/wallix/redemption/blob/future/src/mod/rdp/rdp.cpp#L115 which can create a `SesmanEventPtr` to wait for a answer. This also makes it unnecessary to add `AuthApi::send` because the main loop already does it.

```cpp
// SessionReactor::SesmanEventPtr
private_rdp_negociation.sesman_event = this->session_reactor.create_sesman_event()
.on_action([this, &](JLN_ACTION_CTX ctx, Inifile& ini){
    // rdp_negociation.....
    // JLN_ACTION_CTX -> https://github.com/wallix/redemption/blob/future/src/core/session_reactor.hpp#L429
    // return ctx.terminate();
    // return ctx.exception(Error(ERR_.....));
}));
```

**Comment by jukeks** [comment]
Removed AuthApi::send.

You probaby answered to this in your previous message, but I didn't quite understand. [Here](https://github.com/wallix/redemption/pull/33/files#diff-697771ea220cc2c85f6c2496c3b4a336R235) I create the sesman event to wait for authentifier response. This wait needs to block or we send credentials to a server which hasn't been authenticated. You suggested returning an enum instead of bool in type ServerCertificateCallback. Would TLSContext::check_certificate or SocketTransport::enable_client_tls handle the "pending" state somehow not immediately obvious to me?

**Comment by jonathanpoelen** [comment]
I realize that my proposal can not work that way.

After thinking, I think `mod_rdp_params.server_cert_callback` should take` X509` + a callback built by RDPNegociation. The latter can then call RDPNegociation to complete the validation of the certificate. Remember that events are asynchronous, therefore `server_notifier.server_cert_callback (px509);` in TLSContext can not return true or false directly, there must be a value to say that we do not know the answer yet. it is at this point that `TLSContext :: enable_client_tls` should have a status 'pending verification' which will call back the callback later.

```cpp
// create_mod_rdp
mod_rdp_params.server_cert_callback([result = State::wait](x509&, std::function<void()> cb) mutable{
  ini.set(....)
  new_mod->sesman_event = ....on_action(jln::one_shot([cb=std::move(cb), &result](Inifile& ini){
    result = State(ini.get<cfg::mod_rdp::server_cert_valid>());
    cb();
  }));
  return result;
});

// rdp_negociation.cpp
this->server_notifier.set_cert_callback([&](X509& x509){
  mod_rdp_params.server_cert_callback(x509, [&]{
    nego... // => trans.enable_client_tls() => mod_rdp_params.server_cert_callback()
  });
});
```

**Comment by jukeks** [comment]
I have updated the merge request, but I'm quite stuck. In `create_module_rdp.cpp:235` I create the callback that restarts the TLS certificate verification, as was described above. However the function exits when creating the sesman event.

https://pastebin.com/fUeD145e

I have tried using gdb to see what is happening but I'm unable to create a breakpoint to the callback.

Here's how I have compiled the project:
```
BOOST_STACKTRACE=1 bjam toolset=gcc-7 cxxflags='-ggdb -DREDEMPTION_DISABLE_NO_BOOST_PREPROCESSOR_WARNING -DREDEMPTION_SERVER_CERT_CALLBACK' rdpproxy && BOOST_STACKTRACE=1 sudo bjam toolset=gcc-7 cxxflags='-DREDEMPTION_DISABLE_NO_BOOST_PREPROCESSOR_WARNING -DREDEMPTION_SERVER_CERT_CALLBACK -ggdb' install
```

I'm wondering could it be an issue with lifetime in the variables I'm capturing to the lambda.

**Comment by pykoder** [comment]
You should try with the branch jpo_cert_validation

**Comment by jukeks** [comment]
Thank you, that works. I've updated the pull request with your changes.

**Comment by jukeks** [comment]
My mystery problems with gdb went away with -N argument to rdpproxy.
