### ISSUE TITLE
Monitor current sessions ?

### ISSUE THREAD

**Issue by dtouzeau** [wallix/redemption#36]
Is it possible to have a tool that generates a table with 

session_id,source_ipaddess, source_username, target_ip:target_port, time elapsed

With possibility to kill a session.

**Comment by pykoder** [comment]
The easiest way to do that is to collect the desired information on the go in the authentifier script (passthrough.py). The rdpproxy process will also tell it's pid. Then killing a session will be as simple as sending a signal (mind it will only kill proxy session, not the RDP session opened on the target server).

**Comment by dtouzeau** [comment]
Understand, 

Thanks... done for me...
