### ISSUE TITLE
Microsoft Remote Desktop for Mac 10 missing fonts on redemption UI

### ISSUE THREAD

**Issue by jukeks** [wallix/redemption#42]
Version 8.0.44 of Microsoft Remote Desktop for Mac works fine with redemption UI, but 10 is missing fonts:

![8.0.44](https://user-images.githubusercontent.com/1302691/57530548-2bb69d00-7340-11e9-924e-de8ab8653115.jpg)
8.0.44
![10.2.13](https://user-images.githubusercontent.com/1302691/57530553-2ce7ca00-7340-11e9-91a9-d74f11f40493.jpg)
10.2.13

Is this an issue with the client or redemption? The client can be downloaded for free on App store.

**Comment by XiaopengZHOU** [comment]
Please add the following lines to the configuration file (by default **/etc/rdpproxy/rdpproxy.ini**) and try again.

```
[client]
transform_glyph_to_bitmap = Yes
```

**Comment by jukeks** [comment]
Thank you, that solves the issue. Why does this happen? Is the client missing the font redemption uses or what?

**Comment by XiaopengZHOU** [comment]
It may well be that the Microsoft Remote Desktop for Mac 10 does not support Glyph.
