### ISSUE TITLE
Convert .mwrm/.wrm capture to video

### ISSUE THREAD

**Issue by firesasin** [wallix/redemption#56]
# /gcc/tools/redrec /gcc/bin/gcc-7/release/libredrec.so -f --video-codec mp4 -i file.wrm -o output_prefix
Output file is "/var/rdpproxy/recorded/rdp/output_prefix".
Error: Open file failed
#

Is the usage correct?

**Comment by jonathanpoelen** [comment]
Input file should be a mwrm file.

**Comment by firesasin** [comment]
How can I generate a mwrm file?

**Comment by jonathanpoelen** [comment]
He is always generated at the same time as the wrm files.

**Comment by firesasin** [comment]
Thank you.
