### ISSUE TITLE
Slow Screen Rendering

### ISSUE THREAD

**Issue by tahmoor** [wallix/redemption#59]
High,
When connecting to an RDP server through Redemption, there is a sensible slow screen rendering. Especially, when creating another RDP connection inside the proxied RDP session, rendering will be much slower. Is there any configuration parameter that can increase rendering speed?

**Comment by pykoder** [comment]
Rendering speed depends much of what is drawn on the screen. Many options can have an effect on drawing time. There is nothing special about using RDP target as a jump server to another target. Of course if both sessions are running on the same network they will share bandwidth, but that should not be an issue with modern networks.

Something you can try is ensure that recording is disabled if you are not using it, including internal image buffer. This means to set the following value in rdpproxy.ini 

[video]
capture_flags = 0

You can also ensure that RDP client and Terminal Server target are using the same color depth this will help for faster proxyfication (anyway redemption is trying to do that by himself if he can).
