### ISSUE TITLE
rdpproxy.ini options --> disconnect_on_logon_user_change = 1

### ISSUE THREAD

**Issue by firesasin** [wallix/redemption#60]
I changed the options.

In file rdpproxy.ini :
disconnect_on_logon_user_change = 1

After changing the option, I cannot connect to the server.

logs :
rdpproxy: INFO (147/147) -- Logon Info Version 2 (data): Domain="WIN-CJ7EQF887VU" UserName="Administrator" SessionId=1
rdpproxy: ERR (147/147) -- Unauthorized logon user change detected on MARK2-PC (administrator) -> (WIN-CJ7EQF887VU\Administrator). The session will be disconnected.
rdpproxy: INFO (147/147) -- mod_rdp::draw_event() state switch raised exception
rdpproxy: INFO (147/147) -- ---<>  Front::must_be_stop_capture  <>---

**Comment by pykoder** [comment]
Yes. If you try to reconnect to some already open session where you are connected with another user, the session disconnect. This is the purpose of the option.
