### ISSUE TITLE
How to define recording path

### ISSUE THREAD

**Issue by jukeks** [wallix/redemption#66]
I have set following attributes on ACL:

```
{
    "is_rec": "true",
    "rec_path": "/trails/<uuid>/",
    "trace_type": "2",
    "encryption_key": "<enc key>",
    "sign_key": "<sign key>",
    "target_host": "<target address>",
    "target_port": "<target port>",
    "target_login": "<target user>",
    "target_password: "<target password>",
    "proto_dest": "RDP",
    "module": "RDP",
    "login": "<target user>",
    "session_id": "<uuid>",
    "enable_server_cert_external_validation": "true",
}
```

And I have compiled this project with `RECORD_PATH=/`.

This creates files in `/trails/<uuid>` called `-000000.wrm` and `.mwrm`. Unfortunately `.mwrm` is not a valid name for `redrec -i` and if I rename the `.mwrm` to `rec.mwrm` it doesn't decrypt due to I'm guessing mismatch in filename.

If I set `"rec_path": "/trails/<uuid>/rec`, I get files `/rec-000000.wrm` and `/rec.wrm`. Now the files have correct name, but incorrect path.

Is there some other parameter in the ACL I could use to produce a valid filename in rec_path?

**Comment by jonathanpoelen** [comment]
For some reasons, if there is a basename, only it is used, otherwise full rec_path, but it is not possible to have both. I think it exists for historical reasons that no longer exist today, I will check next week.

The problem with redrec is probably due to an error in the separation directory, basename, extension.

**Comment by jonathanpoelen** [comment]
There are now 3 new parameters for sesman: `hash_path`, `record_path` and `record_tmp_path` which will replace the value defined in the ini file if sent (default values are `RECORD_PATH`, etc).

The behavior related to `rec_path` has not changed, only the basename is used.
