### ISSUE TITLE
Cannot get rdpproxy work as excpected

### ISSUE THREAD

**Issue by speidy** [wallix/redemption#7]
Hello

I am trying to use rdpproxy with authhook.py in order to have a working RDP proxy setup
like: 
Client -> RDPproxy -> Win7 as  RDP server

I tried several configurations in authhook.py and I also advised the (?) icon for specifying the connection parameters as follows:
Username: RemoteServerUser@RemoteHost:RDP:< user from authhook.py >
Password:  < password from authhook.py >

I cant get it working. Do you have any idea what im doing wrong?

Thanks

**Comment by amits1995** [comment]
+1

**Comment by speidy** [comment]
to be more specific, the module is always stays MODULE_LOGIN
even if I get some other module from authhook.py

state machine still returns:
rdpproxy: INFO (13246/13246) -- ===========> MODULE_LOGIN

**Comment by mengtan** [comment]
Hi,
There's a new script in branch future at tools/passthrough/passthrough.py that will work along side rdpproxy.
This works as a simple passthrough, it does not manage any user or authorizations.
You can just run it with:
$ python tools/passthrough/passthrough.py

Hope this works for you.
Regards

**Comment by amits1995** [comment]
Hi,
The new passthrough script works great, thank you very much!
is there any way to make bjam run without the tests? it's very slow every time we want to compile a different version..

**Comment by mengtan** [comment]
You can run bjam with 'exe' target:
$ bjam -q exe
This will compile executables without tests and be way faster :)

**Comment by amits1995** [comment]
Excellent. Thanks
