### ISSUE TITLE
Debian 9.9 build Fails 

### ISSUE THREAD

**Issue by ciari** [wallix/redemption#80]
Trying to build redemption on debian 9.9 but i 'm getting error below 

> src/transport/ws/ws_protocol.hpp:76:22: error: no member named 'boyer_moore_searcher' in namespace 'std'
>                 std::boyer_moore_searcher(needle.begin(), needle.end()));
>                 ~~~~~^
> 1 error generated.

and 

> ...failed updating 3 targets...
> ...skipped 2 targets...
> ...updated 206 targets...

Also cannot build packages too. Is there any known work around?

**Comment by jonathanpoelen** [comment]
"Instructions" for building a package are in the README: https://github.com/wallix/redemption#packaging and the skeleton of the packages in `packaging/template`.

If `std::boyer_moore_searcher` does not exist, then your standard compiler/library version is not recent enough. Is this the only error?

**Comment by ciari** [comment]
No other errors. on Debian 9.9 package build fails with same error too. But Debian 10 work fine for package building. But on Debian 10, building stretch package, causes libavcodec58 dependency, which is not present on debian stretch repos. building package, and deploying works fine on debian 10.  

i have checked llvm repos, and installed 

> clang clang-11 libclang-common-11-dev libclang1-11 libllvm11 libomp-11-dev libomp5-11 llvm-11 llvm-11-dev llvm-11-runtime libc++-11-dev libc++abi-11-dev gcc git pkg-config make libboost1.67-tools-dev libbz2-dev libx264-dev yasm libavcodec-dev libavformat-dev libswscale-dev libssl-dev zlib1g-dev libsnappy-dev libpng-dev libkrb5-dev

packages to build from source. Otherwise, there were lots of errors. This is the only error i couldnt fix.

**Comment by jonathanpoelen** [comment]
> But on Debian 10, building stretch package, causes libavcodec58 dependency

The packages use a magic variable of dpkg (`${shlibs: Depends}`) which gives the dependencies from the executables. You would have to build the package from stretch or manually add dependencies.

**Comment by ciari** [comment]
this works thank you very much
