### ISSUE TITLE
How to change log level?

### ISSUE THREAD

**Issue by jukeks** [wallix/redemption#88]
redemption is a bit chatty by default. Is there any way to change log level if I'm not interested in INFO level messages?

I didn't find anything related in `rdpproxy --help`

**Comment by jonathanpoelen** [comment]
This can be done by adding filters in `syslog-ng`/`rsyslog` (or other log manager on your system).

**Comment by jonathanpoelen** [comment]
For unit-test, there is the environment variable `REDEMPTION_LOG_PRINT` (`bjam --help` for detail)
