### ISSUE TITLE
RDP Clipboard/Drive redirection support

### ISSUE THREAD

**Issue by miha-x86** [wallix/redemption#9]
I was testing redemption for redirection, and I couldn't make it work.

I'm using the proxy connecting from a Windows 7 machine to a Windows
2008 server via mstsc (with clipboard and sharing all drives on the
settings tab of mstsc.exe) but on connection no extra drive is mounted
and clipboard sharing doesn't work.
And I'm positive that redirection works on that Windows 2008 RDP
server, because I tested it without the use of Redepmtion, connecting
directly.

On the proxy side I've set allow_channels=*, deny_channels=
and the verbosity flag set for mod_rdp, front and session.

When I start a connection I see the debug message deny_channels=EVERY
POSSIBLE CHANNEL. Even thou it's set to nothing in the ini file.

I think this is happening on the update_authorized_channels() function
from AuthorizationChannels class.

Do I need to take any extra steps to make it work? 

I'm using the release 0.9.723.
Running it by using the following commands:
$ python ./passthrough.py
\# /usr/local/bin/rdpproxy -nf

Please check the ini file and the syslog output attached:
[rdpproxy.ini.txt](https://github.com/wallix/redemption/files/403859/rdpproxy.ini.txt)
[log.txt](https://github.com/wallix/redemption/files/403853/log.txt)

Thanks for the help.

**Comment by jonathanpoelen** [comment]
`disable_proxy_opt` must be activated to disable update_authorized_channels() function.

The name of the option is badly chosen and the default value does not make sense here, I'll watch Monday.

```
[globals]
disable_proxy_opt=yes
```

**Comment by miha-x86** [comment]
That option worked, redirection is OK now.
Thanks for the help.
